events {
    worker_connections 1024;
}

stream {
    # Upstream para consultas de lectura (SELECT)
    upstream mysql_reads {
        least_conn;
        server db_slave1:3306;
        server db_slave2:3306;
    }

    # Balanceo para consultas de lectura
    server {
        listen 3306;  # Puerto para lecturas
        proxy_pass mysql_reads;
    }
}
